### ISSUE TITLE
Review AutoGenerateBindingRedirects

### ISSUE THREAD

**Issue by hangy** [d-velop/dvelop-app-template-cs#25]
https://github.com/d-velop/dvelop-app-template-cs/blob/1510d74f34fe89dc16bfdd20e67f0fa4c7b52ae6/AwsLambda/Entrypoint/EntryPoint.csproj#L11
As far as I know, this should be a [boolean value](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection#enable-automatic-binding-redirects-manually)?

**Comment by ckuetbach** [comment]
You are absolute right ... I will check this.

Thanks.

**Comment by ckuetbach** [comment]
I removed the redirect, because it was not needed. Not sure if this element still exists for .net core application.
