### ISSUE TITLE
Update terraform versions in buildcontainer

### ISSUE THREAD

**Issue by mtestrot** [d-velop/dvelop-app-template-cs#29]
cf. https://github.com/d-velop/dvelop-app-template-go/commit/518e4a62ae0228ebac76bdf48e51b34964dc55a0

**Comment by ckuetbach** [comment]
Fixed with: https://github.com/d-velop/dvelop-app-template-cs/commit/25e93403971142257d4d9c3e3b9ca35459e6494d
