### ISSUE TITLE
Deactivate hosted zone module

### ISSUE THREAD

**Issue by mtestrot** [d-velop/dvelop-app-template-cs#30]
cf. https://github.com/d-velop/dvelop-app-template-go/commit/2b205874b3fcf01f1c3c7f3365a7d41a7c87d4eb

**Comment by ckuetbach** [comment]
Fixed with: https://github.com/d-velop/dvelop-app-template-cs/commit/25e93403971142257d4d9c3e3b9ca35459e6494d
