### ISSUE TITLE
Docs talks about AWS Access and secret key but not about signature secret...

### ISSUE THREAD

**Issue by dmpe** [d-velop/dvelop-app-template-cs#36]
Thus, how do i set it up ? I want to use `deploy` command and deploy it automatically to aws. But get `AuthorizationHeaderMalformed` when calling CreateBucket operation, error 255, line 45 in 
`makefile`

Thank you!

**Comment by ckuetbach** [comment]
Hello, 

I think there are two issues:

1. The `SIGNATURE_SECRET` will be generated by the [d.velop cloud platform](https://my.d-velop.cloud), if you register an Application.
The value needs to exist in your environment and can be set like the AWS credentials. 
`SET SIGNATURE_SECRET=<paste from my.d-velop.cloud>` or  `export SIGNATURE_SECRET=<paste from my.d-velop.cloud>`

2.  The line and error seems more like a problem with your AWS credentials. The terraform-backend and other resources already exists in my account and therefor cannot be created in your account. The S3 bucket names for example needs to be worldwide unique.

Did you [rename your application](https://github.com/d-velop/dvelop-app-template-cs#rename-the-app)?

**Comment by dmpe** [comment]
Hi, 
thank you. It is helps me a lot. I will try next week and let you know in case of anything. Closing for now...

**Comment by dmpe** [comment]
solved now
env is not config file, thus is must remained empty, without any keys.

**Comment by ckuetbach** [comment]
I think I can close this Issue, the readme is more precise now.
