### ISSUE TITLE
icon property in FeatureDTO should be iconURI

### ISSUE THREAD

**Issue by mtestrot** [d-velop/dvelop-app-template-cs#53]

**Comment by mtestrot** [comment]
cf. https://developer.d-velop.de/documentation/dhapi/de

**Comment by ckuetbach** [comment]
Do you mean the Case of the property?

The serialize and deserialize ind newtonsoft JSON are case insensitive by default. System.Text.Json can also handle property names case insensitive.

**Comment by mtestrot** [comment]
No... Not the case, The template uses the property 

> icon 

but the Home-App docu specifies 

> iconURI

**Comment by ckuetbach** [comment]
Ahh, I see.

`icon` is deprecated and shouldn't be used anymore.
