### ISSUE TITLE
ProduceAttribute: If only */* is given as accept header, use text/html as default

### ISSUE THREAD

**Issue by sterschl** [d-velop/dvelop-app-template-cs#60]
`Accept: image/gif, image/jpeg, image/pjpeg, application/x-ms-application, application/xaml+xml, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*`

In this example no valid route is found, although there is a handler for text/html.

**Comment by ckuetbach** [comment]
fixed with #61
